---
# Common
net: UNetpp # UNet, RDAUNet, UNet2, UNetpp
bilinear: True
n_epochs: 3000
batch_size: 16
dataset: dataset2.yaml
workers: 9
cache: ram # ram or disk
data_augmentation: True
tensorboard: True
pretrained_weights: False
random_seed: 42

optimizer: RMSProp # Adam, RMSProp
adam_beta1: 0.9
adam_beta2: 0.999

# Unet trainers
learning_rate: 0.00025
pretrained_weights_path: /workspace/shared_files/TFM/Code/experiments/exp36/weights/best.pt

# Unet with WGan trainers
pretrained_weights_path_generator: /workspace/shared_files/TFM/Code/experiments/exp36/weights/best.pt
pretrained_weights_path_critic: /workspace/shared_files/TFM/Code/experiments/exp36/weights/best.pt
critic: Critic1 # Critic1

generator_learning_rate: 0.0002
critic_learning_rate: 0.0002

n_critic: 5