---
# Common
net: UNetpp # UNet, RDAUNet, UNet2, UNetpp, TransUNet
bilinear: True
n_epochs: 3000
batch_size: 16
dataset: dataset5.yaml
workers: 9
cache: ram # ram or disk
data_augmentation: True
tensorboard: True
random_seed: 42

optimizer: Adam # Adam, RMSProp
adam_beta1: 0.9
adam_beta2: 0.999

vit_blocks: 8
vit_dim: 512

consistency_term: True
M: 0

# Unet trainers
learning_rate: 0.000075
pretrained_weights_path: /workspace/shared_files/TFM/Code/experiments/exp22/weights/best.pt
pretrained_weights: False

# Unet with WGan trainers
pretrained_weights_generator: True
pretrained_weights_critic: False
pretrained_weights_path_generator: /workspace/shared_files/TFM/Code/experiments/exp22/weights/last.pt
pretrained_weights_path_critic: /workspace/shared_files/TFM/Code/experiments/exp36/weights/best.pt
critic: Critic3_CT_WGAN # Critic1, Critic2, Critic3_CT_WGAN

generator_learning_rate: 0.000005
critic_learning_rate: 0.00003

n_critic: 5