---
######################
######## UNET ########
######################
# Common
net: UNet # UNet, RDAUNet, UNet2, UNetpp, UnetSharp, RCAIUNet, SegNet_VGG19
grayscale: True
bilinear: True
n_epochs: 150
batch_size: 32
dataset: dataset6.yaml
workers: 16
cache: ram # ram or disk
data_augmentation: True
tensorboard: False
random_seed: 42

optimizer: Adam # Adam, RMSProp
adam_beta1: 0.9
adam_beta2: 0.999

remote: False
change_string: /workspace/shared_files/
new_string: /home/imartinez/
#new_string: D:\
multi_gpu: False
device: 'cuda:1'

# Unet trainers
learning_rate: 0.00025
pretrained_weights_path: /home/imartinez/Code/experiments/exp40/weights/last.pt
pretrained_weights: False
adversarial_training: True
epsilon: 0.1

# UnetSharp
nc: 16
pooling: Hartley # Max, Hartley, Hybrid
dropout: dropblock # dropout, dropblock, None
block_size: 3 # Dropblock


